[feat]card component
19-Takify/19-taskify pull request #11
Opened 2024-04-16 05:12 UTC by skoo1100

## 💡 이슈 번호 ('- #이슈번호' 로 작성하세요)

- #6 

## 💬 PR 타입 (하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 디자인 수정
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 🌵 반영 브랜치 ex) feat/hello -> dev
 feat/card-component -> dev

## 🔎 작업 내용
대시보드에 사용하는 카드 컴포넌트 작업

## 🖼️ 스크린샷 (선택)
![스크린샷 2024-04-16 111406](https://github.com/19-Takify/19-taskify/assets/55544307/c3c96dd6-3ee2-45c2-b08a-6d3838149bc9)

## 💬 리뷰 요구사항
아직은 안보셔도 될 꺼 같습니다.. 나중에 작업하려구요
api 받아서 해야될 꺼 같아서 나중에 다시 작업하겠습니다.

2024-04-16 05:25 UTC, woo29 commented
고생하셨습니다👍🔥👍🔥👍🔥👍🔥👍🔥👍🔥

![로봇](https://github.com/19-Takify/19-taskify/assets/162881886/a249479e-a0f5-417b-b1be-4d67834a6543)

2024-04-16 11:05 UTC, woo29 requested changes

2024-04-17 02:21 UTC, skoo1100 commented on src/components/Card/Card.module.scss
> +  gap: 10px;
rem으로 바꾸겠습니다!

2024-04-17 02:22 UTC, skoo1100 commented on src/components/Card/index.tsx
> +        />
네 스타일 설정 해야겠네요 감사합니다!

2024-04-17 02:22 UTC, skoo1100 commented on src/components/Card/Card.module.scss
> +  background: #f9eee3;
굳굳!!
바꾸겠습니다!

2024-04-18 05:12 UTC, devwqc commented on src/components/Button/Button.module.scss
> +}
p4; 이렇게도 가능하지 않을까 싶어요!

```suggestion
.sign {
  background: $color-violet-5534da;
  width: 32.5rem;
  height: 3rem;
  border-radius: 0.5rem;
  font-size: 1.25rem;
  font-weight: 500;
  color: $color-white-ffffff;
  
  &:disabled {
  background: $color-gray-9fa6b2;
}

  @include mobile {
    width: 22rem;
  }
}
```

2024-04-18 05:12 UTC, devwqc commented on src/components/Card/Card.module.scss
> +.tags li {
p3; 태그 선택자가 보이는데 해당 부분은 클래스 선택자로 바꾸면 더 좋을 거 같습니다👍

2024-04-18 05:12 UTC, devwqc commented on src/components/Card/index.tsx
> +          alt=" card 배경 이미지"
p5; card 배경 이미지 앞에 공백이 하나 있는데 이건 상관 없는 건가요??

2024-04-18 05:12 UTC, devwqc commented on src/styles/reset.scss
> +
💯

2024-04-18 07:33 UTC, skoo1100 commented on src/components/Card/index.tsx
> +          alt=" card 배경 이미지"
오.. 몰랐네요 바꾸겠습니다.

2024-04-18 08:13 UTC, woo29 approved these changes

2024-04-18 09:39 UTC, skoo1100 commented
feat/sidemenu-component 쪽에 병합했습니다!

2024-04-19 03:10 UTC, merged