Feat/sidemenu component
19-Takify/19-taskify pull request #14
Opened 2024-04-16 10:15 UTC by skoo1100

## 💡 이슈 번호 ('- #이슈번호' 로 작성하세요)

- #10 

## 💬 PR 타입 (하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 디자인 수정
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 🌵 반영 브랜치 ex) feat/hello -> dev
feat/sidemenu-component -> dev

## 🔎 작업 내용
사이드 메뉴 컴포넌트 작업했습니다.

## 🖼️ 스크린샷 (선택)
![스크린샷 2024-04-16 174016](https://github.com/19-Takify/19-taskify/assets/55544307/366de36d-3448-4e12-a23f-b0550c7b1c30)

## 💬 리뷰 요구사항
![스크린샷 2024-04-16 191157](https://github.com/19-Takify/19-taskify/assets/55544307/5df29ba3-7ace-4ab8-8eaf-cf830f6bcb77)

나의 대시보드를 보면 사이드 메뉴와 내 대시보드가 겹치더라고여
지금은 따로 작업을 했는데 공통으로 묶을려고 합니다. 
그런데 내 대시보드가 필요 없다고 생각하는데 저만 그런걸까요..?

2024-04-16 10:59 UTC, woo29 requested changes

2024-04-16 10:59 UTC, woo29 commented on public/svgs/taskify.svg
이거는 로고랑 같이 다운 받거나 없어도 될 것 같네요 사용해도 텍스트 이미지만 사용할 일이 없을 것 같아서...

2024-04-16 10:59 UTC, woo29 commented on src/components/SideMenu/index.tsx
> +        />
같이 사용하는거면 이미지 같이 다운받고 하나로 사용하는게 더 좋아보이네요!!

2024-04-16 10:59 UTC, woo29 commented on src/components/SideMenu/index.tsx
> +            <li key={index} className={styles.dashboardList}>
```suggestion
            <li key={index} className={styles.dashboardList}>
```
대시보드는 나중에 삭제될 수 있는 요소인 것 같아서 데이터 받으면 id 같은걸로 넣으면 좋을 것 같아요!

2024-04-16 11:13 UTC, devwqc commented on src/components/Button/Button/Button.module.scss
> +}
지금은 반응형을 선택자 안에서 작업하셨는데 최하단에 한번에 묶으면 반응형을 관리하기 더 쉬울 거 같아요!
```scss
@include tablet {
  .deny {
    width 4.5rem;
  }
  .column {
    width: 34rem;
  }

  ...

}
```

2024-04-16 11:26 UTC, skoo1100 commented on public/svgs/taskify.svg
오호 이미지 다시 받아야겠네요 ㅎ

2024-04-16 11:27 UTC, skoo1100 commented on src/components/SideMenu/index.tsx
> +            <li key={index} className={styles.dashboardList}>
id로 바꿀께용

2024-04-16 11:27 UTC, skoo1100 commented on src/components/Button/Button/Button.module.scss
> +}
반응형 중복 없이 깔끔하네요!
이렇게 해야겠습니다 감사합니다.

2024-04-16 11:33 UTC, devwqc commented on src/components/Button/Button/index.tsx
> +      text: '',
해당 부분에 대한 코멘트는 https://github.com/19-Takify/19-taskify/pull/4 여기에 달았습니다!

2024-04-16 11:33 UTC, devwqc commented on src/components/Button/ButtonDashboard/index.tsx
> +}: ButtonDashboardProps<string | boolean | number>) {
혹시 해당 타입에 대한 설명 가능할까요...?
이렇게 사용하는 건 처음봐서 잘 모르겠습니다!

2024-04-16 12:04 UTC, woo29 approved these changes

2024-04-16 12:27 UTC, skoo1100 commented on src/components/Button/ButtonDashboard/index.tsx
> +}: ButtonDashboardProps<string | boolean | number>) {
string이나 boolean이나 number 가 value에 들어오는걸로 아는데 자세힌 모르겠습니다 ㅠ

2024-04-16 13:20 UTC, woo29 commented on src/components/Button/Button/Button.module.scss
> +}
저는 승구님처럼 사용하는데 최하단에서 다 사용하면 오히려 관리하기 더 어렵지 않을까요??
css 라인 수가 적으면 체감이 덜 가는 것 같긴한데 라인 수가 좀 길다고 가정하면 .deny만 수정하려고 하는데 위로 스크롤하고 아래로 스크롤해서 왔다갔다하면 오히려 더 불편할 것 같다고 생각하는데 멘토님한테 여쭤보는 것도 좋을 것 같네요!
(저도 처음에는 최하단에 썼다가 이전 멘토님 추천으로 바꿨었습니다🙃)

2024-04-17 09:52 UTC, devwqc approved these changes
승구님!! 쉬엄쉬엄 하세요 💯

2024-04-18 07:06 UTC, q45402sk approved these changes

2024-04-18 09:37 UTC, merged