[Feat] header 컴포넌트
19-Takify/19-taskify pull request #23
Opened 2024-04-18 02:20 UTC by yb3143

## 💡 이슈 번호 ('- #이슈번호' 로 작성하세요)

- #9 

## 💬 PR 타입 (하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 디자인 수정
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 🌵 반영 브랜치 ex) feat/hello -> dev

## 🔎 작업 내용

## 🖼️ 스크린샷 (선택)

## 💬 리뷰 요구사항

2024-04-18 02:31 UTC, woo29 commented
수고하셨습니다~~~
전체적으로 Image 컴포넌트 크기랑 alt 값들 수정하면 좋을 것 같아요!
![룩](https://github.com/19-Takify/19-taskify/assets/162881886/bfac1d21-2433-4c05-a9b2-bc20c9f5e790)

2024-04-18 04:12 UTC, skoo1100 approved these changes

2024-04-18 04:12 UTC, skoo1100 commented on src/components/Header/DashBoard/DashBoard.module.scss
> +  cursor: pointer;
저희 reset.css에 button 태그는 
cursor: pointer가 적용되어 있어요!

2024-04-18 04:13 UTC, skoo1100 commented
고생하셨습니다!
프로필 아이콘은 제가 적용해볼께용 ㅎㅎ

2024-04-18 05:11 UTC, woo29 requested changes

2024-04-18 06:08 UTC, devwqc commented on src/components/Modal/Potal.tsx
> +  const el: any = document.getElementById('modal-root');
요기 any 빼도 되지 않나요?!
```suggestion
const el = document.getElementById('modal-root');
```

2024-04-18 06:09 UTC, devwqc commented on src/components/Modal/Potal.tsx
> +  const el: any = document.getElementById('modal-root');
아아!! 혹시 여기에 타입이 없어서 build 에러 났던건가요?

2024-04-18 06:13 UTC, devwqc reviewed
유빈님 잘하고 계신 거 같아요!!
모달 어렵지만 잘 해내실 수 있습니다👍
<img src="https://github.com/19-Takify/19-taskify/assets/98067115/ad4a4958-e454-4a4f-b5fb-efd19208f735" width="40%" />

2024-04-18 06:45 UTC, yb3143 commented on src/components/Modal/Potal.tsx
> +  const el: any = document.getElementById('modal-root');
네ㅠㅜ

2024-04-18 12:31 UTC, skoo1100 commented on src/components/Header/DashBoard/DashBoard.module.scss
> +  background-color: black;
$color-black-000000

2024-04-19 03:17 UTC, woo29 approved these changes

2024-04-19 04:24 UTC, q45402sk approved these changes

2024-04-19 14:10 UTC, SeolJaeHyeok commented
지금 정적 파일 관리를 `/public`에서 사용하고 있는데 `/public`의 경우 빌드할 때 포함이 되지 않기 때문에 추후에 이미지를 변경하고 재배포 했을 때 변경된 이미지가 적용되지 않거나 하는 문제가 발생할 여지가 있어요!

그래서 이미지, 폰트 같은 정적 파일은 `/src/assets/images`, `/src/assets/fonts`와 같이 src 경로 내에서 관리해주는게 좋습니다!

2024-04-21 09:29 UTC, devwqc approved these changes

2024-04-21 09:29 UTC, devwqc commented on src/pages/_document.page.tsx
> +        <div id="modal-root"></div>
👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇👍💯🥇

2024-04-23 02:24 UTC, merged