Feat/signup page
19-Takify/19-taskify pull request #30
Opened 2024-04-18 15:55 UTC by devwqc

## 💡 이슈 번호 ('- #이슈번호' 로 작성하세요)

- #28 

## 💬 PR 타입 (하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 디자인 수정
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 🌵 반영 브랜치 ex) feat/hello -> dev
feat/signup-page -> develop

## 🔎 작업 내용
- 회원가입 페이지 디자인 & 회원가입 기능 구현
- Input 컴포넌트 자동완성 브라우저 스타일링 제거

## 🖼️ 스크린샷 (선택)
![signup](https://github.com/19-Takify/19-taskify/assets/98067115/801886a1-d632-4609-a40d-30094ee3bc99)

## 💬 리뷰 요구사항
페이지 컴포넌트 안에 로직을 최소화 하려고 SignupForm을 만들었습니다! 이렇게 분리하는 것에 대해 어떻게 생각하시는지 궁금합니다.
제가 CSS에 많이 미숙합니다. 부족한 점 알려주시면 정말 감사하겠습니다.

2024-04-18 16:07 UTC, devwqc commented on src/pages/signup/index.page.tsx
> +        />
로고 누르면 메인 페이지로 이동할 수 있게 `<Link />`로 감싸겠습니다!

2024-04-19 00:36 UTC, woo29 requested changes

2024-04-19 00:36 UTC, woo29 commented on src/components/Inputs/Input/Input.module.scss
> +    box-shadow: 0 0 0 1000px $color-white-ffffff inset;
```suggestion
    -webkit-box-shadow: 0 0 0 1000px $color-white-ffffff inset;
    box-shadow: 0 0 0 1000px $color-white-ffffff inset;
```
요건 무슨 코드에요??

2024-04-19 00:36 UTC, woo29 commented on src/pages/signup/components/SignupForm/index.tsx
> +      router.push('/login');
```suggestion
      setToast('success', '가입이 완료되었습니다.');
      router.push('/login');
```
회원가입 하고 바로 토큰 넣어서 대시보드 페이지로 가도 좋을 것 같아요 페이지가 이동되니깐 토스트를 굳이 사용안해도 될 것 같네요??

2024-04-19 00:36 UTC, woo29 commented on src/pages/signup/components/SignupForm/index.tsx
> +          e.response?.data.message || '다른 이메일을 입력해 주세요.';
```suggestion
        const message =
          e.response?.data.message || '다른 이메일을 입력해 주세요.';
```

`e.response?.data.message`는 어떤 메세지가 들어오는건가요??

2024-04-19 00:36 UTC, woo29 commented on src/pages/signup/components/SignupForm/index.tsx
> +      reset();
```suggestion
        setError('email', { message });
        return;
      }
      setToast('warn', '다시 시도해 주세요.');
      reset();
```
`setError`로 어떤 이유로 회원가입이 안되는지 알려주니깐 토스트까지 사용할 필요가 없을 것 같아요!
`reset `은 인풋을 지워주는거? 같은데 회원가입 실패하면 모든 인풋에 값이 사라지는건가요??

2024-04-19 00:36 UTC, woo29 commented on src/pages/signup/components/SignupForm/index.tsx
> +          hasLabel={true}
```suggestion
          hasLabel={true}
```
hasLabel만 적어도 true로 될 것 같네요?

2024-04-19 00:36 UTC, woo29 commented on src/pages/signup/components/SignupForm/index.tsx
> +      <PageButton disabled={!isValid}>가입하기</PageButton>
```suggestion
      <PageButton disabled={!isValid}>가입하기</PageButton>
```
저는 버튼이나 인풋 기본 값이 있어도 사용처에서 타입을 명시해주는게 좋다고 생각하는데 불필요할까요??

2024-04-19 00:36 UTC, woo29 commented on src/pages/signup/index.page.tsx
> +          alt="Taskify"
```suggestion
          alt="Taskify"
```
눈 감고 이 alt 값을 스크린 리더가 읽어주면 어떤 이미지라고 연상하기 어려울 것 같아요 Taskify 로고 이런식으로 적어도 좋을 것 같네요!

2024-04-19 01:29 UTC, devwqc commented on src/components/Inputs/Input/Input.module.scss
> +    box-shadow: 0 0 0 1000px $color-white-ffffff inset;
> 요건 무슨 코드에요??

input type에 충족되는 값이 들어갈 경우 크롬 브라우저에서 하늘색 배경의 스타일링이 들어가는 것을 제거하는 코드인데 `reset.scss`에 넣는게 더 좋을 거 같네요👍
![스크린샷 2024-04-19 102828](https://github.com/19-Takify/19-taskify/assets/98067115/6acb23fb-8296-48ca-9e88-b914c25d6847)

2024-04-19 01:31 UTC, devwqc commented on src/pages/signup/components/SignupForm/index.tsx
> +          e.response?.data.message || '다른 이메일을 입력해 주세요.';
> `e.response?.data.message`는 어떤 메세지가 들어오는건가요??

API에서 넘겨준 메세지를 출력하는 거예요~

![스크린샷 2024-04-19 103028](https://github.com/19-Takify/19-taskify/assets/98067115/131c6244-2814-494e-80d4-fcbd2f306d34)

2024-04-19 01:35 UTC, devwqc commented on src/pages/signup/components/SignupForm/index.tsx
> +      reset();
> `setError`로 어떤 이유로 회원가입이 안되는지 알려주니깐 토스트까지 사용할 필요가 없을 것 같아요! `reset `은 인풋을 지워주는거? 같은데 회원가입 실패하면 모든 인풋에 값이 사라지는건가요??

아래 코드는 `axios` error가 아닌 경우일 때의 에러 처리인데 현재 상태에선 `axios` 말고는 catch 문으로 넘어갈 일이 없긴 하지만 있으면 좋을 거 같아서 작성했습니다!
`reset()`은 모든 인풋이 사라지는 거 맞아요! 아래로 넘어왔다는 거는 특정 `Input`의 에러를 특정할 수 없어서 회원가입 버튼이 계속 활성화 되어있고 그럴 경우 버튼을 계속 누를 수 있기 때문에 초기화를 진행하는 게 좋을 거 같다고 판단했습니다.
```ts
setToast('warn', '다시 시도해 주세요.');
reset();
```

2024-04-19 01:37 UTC, devwqc commented
> 고생하셨습니다 form도 따로 분리해주신 것도 너무 좋은 것 같은데 `SignupForm`에서 `AuthForm`으로 바꾸고 로그인 페이지에서까지 사용할 수 있게 해주는 건 어떨까요?? 어차피 차이가 인풋 개수? 그정도 차이일 것 같아서 같이 써도 좋을 것 같네요! url path도 상수화 한번 해줘도 좋을 것 같네요 이 부분은 제가 메인 페이지 PR에 추가해서 푸쉬할게요!

로그인 페이지에서 사용할 수 있게 해준다는 게 컴포넌트 하나로 사용하는 것을 의미하는 걸까요?
만약 회원가입 페이지의 `AuthForm`과 로그인 페이지의 `AuthForm`이 각각 존재하면 이름을 다르게 하는 건 어떨까 싶어요! `import` 해올 때도 직관적일 거 같고

2024-04-19 03:20 UTC, woo29 commented
> > 고생하셨습니다 form도 따로 분리해주신 것도 너무 좋은 것 같은데 `SignupForm`에서 `AuthForm`으로 바꾸고 로그인 페이지에서까지 사용할 수 있게 해주는 건 어떨까요?? 어차피 차이가 인풋 개수? 그정도 차이일 것 같아서 같이 써도 좋을 것 같네요! url path도 상수화 한번 해줘도 좋을 것 같네요 이 부분은 제가 메인 페이지 PR에 추가해서 푸쉬할게요!
> 
> 로그인 페이지에서 사용할 수 있게 해준다는 게 컴포넌트 하나로 사용하는 것을 의미하는 걸까요? 만약 회원가입 페이지의 `AuthForm`과 로그인 페이지의 `AuthForm`이 각각 존재하면 이름을 다르게 하는 건 어떨까 싶어요! `import` 해올 때도 직관적일 거 같고

지금 만들어주신 form에서 분기 처리 하나 생성해서 로그인, 회원가입 두 페이지에서 하나의 AuthForm으로 하는 걸 생각했었어요 
{isRegister && <닉네임 인풋> <비밀번호 확인 인풋>}

2024-04-19 06:23 UTC, q45402sk approved these changes

2024-04-19 14:07 UTC, SeolJaeHyeok commented on src/pages/signup/components/SignupForm/index.tsx
> +          e.response?.data.message || '다른 이메일을 입력해 주세요.';
[여기](https://github.com/19-Takify/19-taskify/pull/32#discussion_r1572425636)와 마찬가지로 서버 에러 메시지는 별도의 파일로 구분해서 관리하는게 좋을거 같은데 어떻게 생각하실까요?!?

2024-04-19 15:37 UTC, devwqc commented on src/pages/signup/components/SignupForm/index.tsx
> +          e.response?.data.message || '다른 이메일을 입력해 주세요.';
> [여기](https://github.com/19-Takify/19-taskify/pull/32#discussion_r1572425636)와 마찬가지로 서버 에러 메시지는 별도의 파일로 구분해서 관리하는게 좋을거 같은데 어떻게 생각하실까요?!?

너무 좋은 거 같아요!! 에러 메세지도 중복되는 경우가 많아서 상수로 분리하면 좋겠습니다👍
아래 코드로 분리해 봤는데 멘토님 의견이 궁금합니다!
```ts
export const LENGTH_ERROR_MESSAGE = {
  MAX: {
    TEN: '10자 이하로 입력해 주세요.',
  },
  MIN: {
    EIGHT: '8자 이상 입력해 주세요.',
  },
};

export const AUTH_ERROR_MESSAGE = {
  EMAIL: {
    EMPTY: '이메일을 입력해 주세요.',
    INVALID: '이메일 형식으로 입력해 주세요.',
    DUPLICATE: '이미 사용중인 이메일입니다.',
  },
  PASSWORD: {
    EMPTY: '비밀번호를 입력해 주세요.',
    NOT_MATCH: '비밀번호가 일치하지 않습니다',
  },
  NICKNAME: {
    EMPTY: '닉네임을 입력해 주세요.',
  },
};
```

2024-04-21 04:40 UTC, woo29 approved these changes

2024-04-21 04:40 UTC, woo29 commented on src/constants/errorMessage.ts
> +};
관심사별로 분리한거 좋은 것 같네요!
```js
INVALID: '이메일 형식으로 입력해 주세요.',
EMPTY: '비밀번호를 입력해 주세요.',
EMPTY: '닉네임을 입력해 주세요.',
```
이 에러들은 저희가 zod 사용해서 버튼을 disabled 하게 막아둬서 없애도 괜찮을 것 같네요!
```js
UNKNOWN: '알 수 없는 오류가 발생했습니다.',
```
이 에러 메세지는 알 수 없는 오류인데 유저 입장에서 어떻게 대처하지? 라는 생각이 들 것 같아서 `"잠시 후 다시 시도해 주세요."` 이런 걸로 문구를 바꾸는 건 어떨까요??

2024-04-21 04:40 UTC, woo29 commented on src/pages/signup/Signup.module.scss
> +  padding-right: 0.75rem;
```suggestion
  padding-left: 0.75rem;
  padding-right: 0.75rem;
```
사소하긴 하지만 이렇게 바꿔도 좋을 것 같네요!
```css
padding: 0 0.75rem
```

2024-04-21 04:40 UTC, woo29 commented on src/pages/signup/components/SignupForm/index.tsx
> +            setError('email', { message: SERVER_ERROR_MESSAGE.EMAIL.INVALID });
zod 사용해서 Invalid 에러를 방지해서 없어도 될 것 같아요!

2024-04-21 04:40 UTC, woo29 commented on src/pages/signup/components/SignupForm/index.tsx
> +              message: SERVER_ERROR_MESSAGE.EMAIL.ALTERNATE,
`다른 이메일을 입력해 주세요.` 
이 에러는 어느 경우에 발생하는거에요??

2024-04-21 04:40 UTC, woo29 commented on src/pages/signup/index.page.tsx
> +        <Link href="/">
```suggestion
        <Link href="/">
```
여기도 url 상수화 사용해도 좋을 것 같네요!

2024-04-21 04:40 UTC, woo29 commented on src/pages/signup/index.page.tsx
> +          <Link href="/login" className={styles.link}>
```suggestion
          <Link href="/login" className={styles.link}>
```
여기도 상수화가 적용이 안되있네요!

2024-04-21 05:48 UTC, devwqc commented on src/pages/signup/components/SignupForm/index.tsx
> +      reset();
> axios error가 아닌 경우?가 어떤 말일까요??

지금 코드로는 axios 에러 말고는 특별히 에러 날 상황이 없긴 하지만 catch문에 axios 에러를 if문으로 에러 핸들링을 해주고 있는데 저희가 모르는 어떤 에러가 try에서 났을 경우를 대비해서 작성했어요!

2024-04-21 05:50 UTC, devwqc commented on src/pages/signup/components/SignupForm/index.tsx
> +            setError('email', { message: SERVER_ERROR_MESSAGE.EMAIL.INVALID });
> zod 사용해서 Invalid 에러를 방지해서 없어도 될 것 같아요!

zod로 방지하긴 했지만 프론트에서 얼마든지 이런 검증을 회피할 수 있어서 저는 검증은 프론트, 백 둘 다 거쳐야 한다고 생각해요!

2024-04-21 05:54 UTC, devwqc commented on src/pages/signup/components/SignupForm/index.tsx
> +              message: SERVER_ERROR_MESSAGE.EMAIL.ALTERNATE,
> `다른 이메일을 입력해 주세요.` 이 에러는 어느 경우에 발생하는거에요??

서버 API에서 현재는 `400`, `404`, `409`를 넘겨주고 있는데 만약에 상태가 추가 됐을 경우 default가 없으면 프론트에선 에러를 감지할 수 없어서 설정했어요
지금은 default로 넘어갈 일은 없어요!

2024-04-21 07:10 UTC, woo29 commented on src/pages/signup/components/SignupForm/index.tsx
> +            setError('email', { message: SERVER_ERROR_MESSAGE.EMAIL.INVALID });
zod로 버튼을 disabled했는데 함수가 실행될 수 있나요?? 
뭐 어떻게 소스 파일 조작해서 했다고 해도 그건 유저가 의도적으로 한거여서 회원가입이 안되도 유저가 감수해야 할 부분 아닐까요??

2024-04-21 22:48 UTC, merged