[feat] 로그인 페이지
19-Takify/19-taskify pull request #32
Opened 2024-04-19 01:11 UTC by q45402sk

## 💡 이슈 번호 ('- #이슈번호' 로 작성하세요)

- #31 

## 💬 PR 타입 (하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 디자인 수정
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 🌵 반영 브랜치 ex) feat/hello -> dev
feat/login-page -> dev

## 🔎 작업 내용
로그인 페이지 기능 구현

## 🖼️ 스크린샷 (선택)

![스크린샷 2024-04-19 100706](https://github.com/19-Takify/19-taskify/assets/56138199/53f4a536-40cc-4dc4-b251-929d96427380)

## 💬 리뷰 요구사항
axios 파일도 수정했습니다. 확인 부탁드립니다.

2024-04-19 01:25 UTC, devwqc commented on src/pages/login/index.page.tsx
> +        setToast('error', String(error));
p3; `setToast('error', error.message);`를 `console.log`로 찍어보면 영어로 출력되고 있어서 사용자 경험으로는 특정한 문구를 입력해 주는게 좋을 거 같아요!
아래 `setToast('error', String(error));`도 `로그인에 실패하였습니다.` 이런 문구를 출력하면 어떨까요?

2024-04-19 01:25 UTC, devwqc commented on src/pages/login/index.page.tsx
>    password: string;
p3; 여기서 네이밍 앞에 I를 붙이는 건 `interface`라는 의미여서 빼는게 좋을 거 같아요👍

2024-04-19 01:32 UTC, woo29 requested changes

2024-04-19 01:32 UTC, woo29 commented on src/pages/login/index.page.tsx
> +        setToast('error', String(error));
```suggestion
      if (isAxiosError(error)) {
        // `AxiosError`인 경우 에러 처리
        if (error.response) {
          setToast('error', error.response.data.message);
        } else {
          setToast('error', error.message);
        }
      } else {
        // `AxiosError`가 아닌 경우
        setToast('error', String(error));
```
If else가 중복되면서 가독성이 떨어지는 것 같은데 early return을 활용해도 좋을 것 같아요! 
그리고 인풋 컴포넌트에 error 메세지 출력하는 곳이 있어서 toast 활용보다는 setError로 넘겨주는게 더 좋을 것 같아요!

2024-04-19 01:32 UTC, woo29 commented on src/pages/login/index.page.tsx
>              hasLabel
```suggestion
            hasLabel
```
true 생략 좋은 것 같아요👍👏👍👏👍👏👍👏👍👏

2024-04-19 01:32 UTC, woo29 commented on src/pages/login/index.page.tsx
>              hasLabel={true}
```suggestion
            hasLabel={true}
```
어 근데 여기는 true가 있네요...?

2024-04-19 01:32 UTC, woo29 commented on src/pages/login/index.page.tsx
> +      <button type="submit">로그인</button>
```suggestion
      <button type="submit">로그인</button>
```
type 명시 너무 좋네요!! 나중에 승구님이 만들어주신 버튼 컴포넌트로 바꿔주기만 하면 될 것 같아요

2024-04-19 02:52 UTC, skoo1100 approved these changes
고생하셨습니다!
완벽합니다!

2024-04-19 03:20 UTC, woo29 approved these changes

2024-04-19 05:15 UTC, q45402sk commented on src/pages/login/index.page.tsx
> +        setToast('error', String(error));
반영했습니다!

2024-04-19 05:15 UTC, q45402sk commented on src/pages/login/index.page.tsx
>    password: string;
반영했습니다!

2024-04-19 05:16 UTC, q45402sk commented on src/pages/login/index.page.tsx
> +        setToast('error', String(error));
반영했습니다!

2024-04-19 14:02 UTC, SeolJaeHyeok commented on src/pages/login/index.page.tsx
> +      }
서버에서 내려주는 메시지들은 지금처럼 하드코딩하는 것보다 별도의 파일로 관리해주는게 좋아요!

[Swagger](https://sp-taskify-api.vercel.app/docs/#/Auth/Login)를 확인하면 어떤 에러 메시지가 나올 수 있는지 정의가 되어 있는거 같으니 별도로 분리해보는건 어떠실까요?!?

2024-04-22 02:29 UTC, devwqc commented on src/pages/login/components/LoginForm/index.tsx
> +      }
메세지로 확인하는 거보다 status로 확인하는게 조금 더 안전할 거 같아요!

2024-04-22 02:59 UTC, q45402sk commented on src/pages/login/components/LoginForm/index.tsx
> +      }
반영했습니다!

2024-04-23 23:45 UTC, SeolJaeHyeok reviewed
마크업 구성하는 능력이 저보다 뛰어나시군요👍👍

2024-04-23 23:45 UTC, SeolJaeHyeok commented on src/pages/index.page.tsx
> +      </Head>
SEO와 관련된 메타 태그들도 별도의 컴포넌트로 관리하면 재사용하기 편해요~!

2024-04-24 00:42 UTC, woo29 commented on src/pages/index.page.tsx
> +      </Head>
> SEO와 관련된 메타 태그들도 별도의 컴포넌트로 관리하면 재사용하기 편해요~!

송은님 이 부분은 제가 맡아서 따로 컴포넌트로 관리할게요!

2024-04-24 00:46 UTC, devwqc approved these changes
송은님 고생하셨어요~~ 파이팅!!💪💯👍

<img src="https://github.com/19-Takify/19-taskify/assets/98067115/5967af41-390f-4139-8a9c-543256e2849b" width="40%" />

2024-04-24 05:53 UTC, merged