[feat] ⚙️ 대시보드 관리 페이지 만들기
19-Takify/19-taskify pull request #38
Opened 2024-04-22 02:41 UTC by woo29

## 💡 이슈 번호 ('- #이슈번호' 로 작성하세요)

- #35 

## 💬 PR 타입 (하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 디자인 수정
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 🌵 반영 브랜치 ex) feat/hello -> dev
feat/invite-log > develop

## 🔎 작업 내용
대시보드 관리 페이지 만들기
- 디자인 가시성이 떨어져서 임의로 테두리 추가했습니다.

jotai 전역 상태 관리 설정 후 작업 예정
- 데이터 패칭 url 추후에 전역 상태 데이터로 변경
- 권한에 따라 버튼 등등 조건부 렌더링 추가

무한 스크롤 커스텀 훅 살려두긴 했는데 무한 스크롤 사용하지 않고 검색 기능을 추가하였습니다.

## 🖼️ 스크린샷 (선택)
https://github.com/19-Takify/19-taskify/assets/162881886/bf69c073-7ce8-4c8c-b08e-50763d52e023

## 💬 리뷰 요구사항
대시보드 관리 페이지 만들기

2024-04-22 03:00 UTC, devwqc commented
무한 스크롤 안 쓰고 검색 구현한 거 너무 좋은데요?👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇👍🥇

소스는 식사 후에 보겠습니다!

2024-04-22 07:58 UTC, devwqc requested changes
코드가 너무 좋아서 리뷰할 것이 크게 없네요...? 훌륭합니다👍

2024-04-22 07:58 UTC, devwqc commented on next.config.mjs
> +  reactStrictMode: false,
이건 `true`로 설정하는 게 좋을 거 같아요👍

2024-04-22 07:58 UTC, devwqc commented on next.config.mjs
> +    domains: ['sprint-fe-project.s3.ap-northeast-2.amazonaws.com'],
👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯

2024-04-22 07:58 UTC, devwqc commented on src/apis/axios.ts
> +const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯👍💯

2024-04-22 07:58 UTC, devwqc commented on src/components/Inputs/DatePicker/DatePicker.module.scss
> -}
혹시 지우신 이유가 있을까요??

2024-04-22 07:58 UTC, devwqc commented on src/pages/dashboard/edit/components/DashboardManager/index.tsx
> +    return () => clearTimeout(timer);
디바운싱까지 적용하셨네요...?😮😮😮

2024-04-22 08:20 UTC, woo29 commented on next.config.mjs
> +  reactStrictMode: false,
저거 dnd 사용할 때 true로 사용하면 충돌나서 dnd가 안되더라구요
https://github.com/atlassian/react-beautiful-dnd/issues/2399#issuecomment-1111169234
https://github.com/atlassian/react-beautiful-dnd/issues/2350
예전 이슈들이긴 한데 최근에 사용했을 때도 strictMode가 켜져있으면 호환이 잘 안되더라구요

2024-04-22 08:21 UTC, woo29 commented on src/components/Inputs/DatePicker/DatePicker.module.scss
> -}
merge만 했고 따로 코드를 건들진 않았는데 원래 있는 css 인가요??

2024-04-23 01:55 UTC, skoo1100 approved these changes
전체적으로 너무 완벽합니다!!
역시 우혁님 !!

2024-04-23 01:55 UTC, skoo1100 commented on src/apis/axios.ts
> +const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
env 좋습니다!!

2024-04-23 01:55 UTC, skoo1100 commented on src/pages/dashboard/edit/components/DashboardManager/index.tsx
> +  };
저도 내 대시보드 페이지에 검색 기능을 구현했는데
컴포넌트로 분리할까요?? 아님 따로 작업하는게 나을까요??

2024-04-23 01:58 UTC, woo29 commented on src/pages/dashboard/edit/components/DashboardManager/index.tsx
> +  };
아마 검색 기능이 저는 클라이언트에서 필터 돌리는거고 승구님은 api에 title를 넘겨줘야 해서 나누는게 좋아보이네요!
<img width="1477" alt="스크린샷 2024-04-23 오전 10 58 26" src="https://github.com/19-Takify/19-taskify/assets/162881886/f21f6248-93eb-4670-b7e9-4f17b2cc56ca">

2024-04-23 05:46 UTC, devwqc commented on src/components/Inputs/DatePicker/DatePicker.module.scss
> -}
> merge만 했고 따로 코드를 건들진 않았는데 원래 있는 css 인가요??

보니까 있어야 하는 css 같아요!

2024-04-23 07:34 UTC, woo29 commented on src/components/Inputs/DatePicker/DatePicker.module.scss
> -}
넵 그럼 이대로 복붙해놓을게요

2024-04-23 07:36 UTC, devwqc approved these changes

2024-04-23 07:50 UTC, merged