[refactor] 버튼 컴포넌트 구조 변경
19-Takify/19-taskify pull request #4
Opened 2024-04-15 10:52 UTC by skoo1100

## 💡 이슈 번호 ('- #이슈번호' 로 작성하세요)
- #1 

## 💬 PR 타입 (하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [x] 기능 변경
- [ ] 기능 삭제
- [ ] 디자인 수정
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 🌵 반영 브랜치 ex) feat/hello -> dev
 feat/button-component -> dev

## 🔎 작업 내용
버튼 컴포넌트를 하나로 합침

## 🖼️ 스크린샷

## 💬 리뷰 요구사항
버튼 컴포넌트를 하나로 묶어버릴까요 아님 분리할까요??

2024-04-15 11:54 UTC, woo29 commented on src/components/Button/ButtonAddCard/ButtonAddCard.module.scss
> +  border: none;
```suggestion
  border: none;
```
reset.css에 추가하신 내용이라 없어도 될 것 같네요!

2024-04-15 12:11 UTC, woo29 commented
버튼 컴포넌트 봤을 때 합치신건 좋은 것 같은데 클래스 네임은 usage 사용안하고 그대로 className으로 넘겨도 좋을 것 같아요!
그리고 children도 지금은 조건문으로 다 설정해주셨는데 이렇게 하면 확장성이 떨어지는 느낌이라서 사실 지금 프로젝트는 요구사항이 늘어나지 않을 것 같긴한데 추후에 요구사항이 늘어난다고하면 더 복잡해질 것 같네요...ㅠㅠ

제가 생각한 코드는 아래 적어놓을게요!!
```js
type TButtonProps = {
  className: string;
  children?: ReactNode;
} & ButtonHTMLAttributes<HTMLButtonElement>;

function Button({ className, children, ...rest }: TButtonProps) {
  return (
    <button className={styles[className]} {...rest}>
      {children}
    </button>
  );
}

function LoginPage() {
  return (
    // 실제로는 onClick 함수 등등 추가
    <Button className="LoginButton" type="submit">
      로그인
    </Button>
  );
}

function DashBoardPage() {
  return (
    /* 
    대시보드 버튼은 색깔 원형, 텍스트, 왕관, 화살표 이미지인데 
    제 생각엔 색깔 원형, 왕관은 저희가 구현하고 화살표 이미지만 넣는 것도 좋을 것 같네요
    다 이미지로 넣는 것보다 성능이 좋아질 것 같아요!
    dashboard.title, dashboard.color = 나중에 서버에서 가져올 값들 
    createdByMe = 내가 만든 대시보드인지 체크
    */
    <Button className="DashBoardButton" type="button">
      <div className={styles.dashboardText}>
        <div className={styles.dashboardName}>
          <ColorCirle color={dashboard.color} />
          <p>{dashboard.title}</p>
          {createdByMe && 👑}
        </div>
        <Image
          src="/svgs/arrow.svg"
          alt="arrow 이미지"
          width={18}
          height={18}
        />
      </div>
    </Button>
  );
}
```

2024-04-15 12:15 UTC, woo29 requested changes

2024-04-15 12:17 UTC, devwqc commented on src/pages/index.page.tsx
> +      <Button usage="dashboardRemove" />
현재 페이지가 존재하지 않아서 다들 공용 컴포넌트를 여기서 만들 거 같은데 이 파일을 push하면 문제가 많이 생길 거 같아요.

2024-04-15 12:18 UTC, woo29 requested changes
버튼 컴포넌트 봤을 때 합치신건 좋은 것 같은데 클래스 네임은 usage 사용안하고 그대로 className으로 넘겨도 좋을 것 같아요! 그리고 children도 지금은 조건문으로 다 설정해주셨는데 이렇게 하면 확장성이 떨어지는 느낌이라서 사실 지금 프로젝트는 요구사항이 늘어나지 않을 것 같긴한데 추후에 요구사항이 늘어난다고하면 더 복잡해질 것 같네요...ㅠㅠ 제가 생각한 코드는 아래 적어놓을게요!! 
```js 
type TButtonProps = {
  className: string;
  children: ReactNode;
} & ButtonHTMLAttributes<HTMLButtonElement>;

function Button({ className, children, ...rest }: TButtonProps) {
  return (
    <button className={styles[className]} {...rest}>
      {children}
    </button>
  );
}

function LoginPage() {
  return (
    // 실제로는 onClick 함수 등등 추가
    <Button className="LoginButton" type="submit">
      로그인
    </Button>
  );
}

function DashBoardPage() {
  return (
    /* 
    대시보드 버튼은 색깔 원형, 텍스트, 왕관, 화살표 이미지인데 
    제 생각엔 색깔 원형, 왕관은 저희가 구현하고 화살표 이미지만 넣는 것도 좋을 것 같네요!
    dashboard.title, dashboard.color = 나중에 서버에서 가져올 값들 
    createdByMe = 내가 만든 대시보드인지 체크
    */
    <Button className="DashBoardButton" type="button">
      <div className={styles.dashboardText}>
        <div className={styles.dashboardName}>
          <ColorCirle color={dashboard.color} />
          <p>{dashboard.title}</p>
          {createdByMe && 👑}
        </div>
        <Image
          src="/svgs/arrow.svg"
          alt="arrow 이미지"
          width={18}
          height={18}
        />
      </div>
    </Button>
  );
}
```

2024-04-15 12:24 UTC, woo29 commented
사소한건데 반영 브랜치 `feat/button-component -> dev` 저희는 `develop`으로 설정되어 있어서 `feat/button-component -> develop`으로 해야할 것 같네요!

2024-04-15 12:29 UTC, woo29 commented
공용 컴포넌트가 생각할게 많은 것 같네요... 만드시느라 고생하셨습니다🙃
![아](https://github.com/19-Takify/19-taskify/assets/162881886/1924d71d-33fa-4881-b3f0-12e2e01c5412)

2024-04-15 13:17 UTC, skoo1100 commented
ㅇ

2024-04-15 13:22 UTC, skoo1100 commented on src/components/Button/ButtonDashboard/index.tsx
> +} & ButtonHTMLAttributes<HTMLButtonElement>;
바꿀 예정입니다 ㅎ

2024-04-15 13:23 UTC, skoo1100 commented on src/pages/index.page.tsx
> +      <Button usage="dashboardRemove" />
네 정리되고 다시 push 할 예정입니다.

2024-04-15 13:23 UTC, skoo1100 commented on src/components/Button/ButtonAddCard/ButtonAddCard.module.scss
> +  border: none;
다시 push할 예정입니다

2024-04-15 15:01 UTC, skoo1100 commented
저는 오히려 className과 children을 객체로 받는게 좋다고 생각했습니다. 
버튼 종류가 생각보다 다양하고 이미지가 들어가는 경우가 있는데 버튼 컴포넌트 하나로 객체로 관리해서 유지 보수 하기 쉽다고 생각합니다.

```js 
function Button({ usage, ...rest }) {
  const BUTTON_TYPE = {
    signin: {
      text: '로그인',
      style: 'sign',
    },
    signup: {
      text: '가입하기',
      style: 'sign',
    },
    card: {
      text: '',
      style: 'card',
      image: '/svgs/add.svg',
      alt: '추가 아이콘',
    },
    column: {
      text: '새로운 컬럼 추가하기',
      style: 'column',
      image: '/svgs/add.svg',
      alt: '추가 아이콘',
    },
    confirm: {
      text: '수락',
      style: 'confirm',
    },
    deny: {
      text: '거절',
      style: 'deny',
    },
    delete: {
      text: '삭제',
      style: 'delete',
    },
    dashboardAdd: {
      text: '새로운 대시보드',
      style: 'dashboard',
      image: '/svgs/add.svg',
      alt: '추가 아이콘',
    },
    dashboardRemove: {
      text: '대시보드 삭제하기',
      style: 'dashboard',
    },
  };

  return (
    <button className={styles[BUTTON_TYPE[usage].style]} {...rest}>
      <div className={styles.buttonText}>
        <p>{BUTTON_TYPE[usage].text}</p>
        {BUTTON_TYPE[usage].image ? (
          <Image
            src={`${BUTTON_TYPE[usage].image}`}
            alt={`${BUTTON_TYPE[usage].alt}`}
            width={16}
            height={16}
          />
        ) : null}
      </div>
    </button>
  );
}
```

2024-04-16 11:27 UTC, devwqc commented on src/components/Button/Button/index.tsx
> +  const BUTTON_TYPE: ButtonType<string> = {
TS의 자동 타입 추론을 적극적으로 사용하면 좋을 거 같아요!
```ts
const BUTTON_TYPE = {
    signin: {
      text: '로그인',
      style: 'sign',
    },
    signup: {
      text: '가입하기',
      style: 'sign',
    },
    card: {
      text: '',
      style: 'card',
      image: '/svgs/add.svg',
      alt: '추가 아이콘',
    },
    ...
}
```

2024-04-18 04:57 UTC, devwqc approved these changes
고생하셨어요 승구님👍
![진지쿵야](https://github.com/19-Takify/19-taskify/assets/98067115/14e64c80-bdc2-4202-91e1-9faf14486558)

2024-04-18 05:44 UTC, q45402sk approved these changes

2024-04-18 08:12 UTC, woo29 approved these changes

2024-04-18 08:50 UTC, merged