[feat] mydashboard 페이지
19-Takify/19-taskify pull request #52
Opened 2024-04-24 12:15 UTC by skoo1100

## 💡 이슈 번호 ('- #이슈번호' 로 작성하세요)

- #34

## 💬 PR 타입 (하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 디자인 수정
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 🌵 반영 브랜치 ex) feat/hello -> dev
feat/mydashboard-page -> develop

## 🔎 작업 내용
mydashboard 페이지 작성

## 🖼️ 스크린샷 (선택)
![스크린샷 2024-04-24 211322](https://github.com/19-Takify/19-taskify/assets/55544307/1054fc91-92b4-4817-9ef8-9831004dfa65)

## 💬 리뷰 요구사항
문제가 많을 꺼 같아서 꼼꼼히 봐주시면 감사하겠습니다! ㅠㅠ

2024-04-24 12:44 UTC, woo29 commented
크게 리뷰할 부분이 없는 것 같네요 수고하셨습니다!!
근데 무한 스크롤 쪽 코드는 주석 처리 되어 있는 것 같은데 주석 처리 하신 이유가 있으신가요??

2024-04-24 12:44 UTC, woo29 requested changes

2024-04-24 12:44 UTC, woo29 commented on src/components/Circle/index.tsx
> +  small: boolean;
```suggestion
  small: boolean;
```
사용할 때 small props 사용 안해도 디폴트 값주셔서 에러 안생기나요??

2024-04-24 12:44 UTC, woo29 commented on src/pages/mydashboard/components/InvitedDashboard/index.tsx
> +              <li key={index}>
```suggestion
              <li key={index}>
```
key에 invitation.id 넣어도 좋을 것 같네요!

2024-04-24 12:44 UTC, woo29 commented on src/pages/mydashboard/components/SearchDashboard/index.tsx
> +        onKeyDown={(e) => handleKeyEnter(e)}
```suggestion
        onKeyDown={(e) => handleKeyEnter(e)}
```
검색 기능이 엔터키 누를때보다 onChange 할 때 나오면 더 좋을 것 같아요!! 검색 api도 호출하시니깐 디바운싱 적용하는 것도 추천드려요
지금은 검색 기능이 클라이언트에서 돌아가고 있는 것 같네요? 이것도 title로 넘겨주셔도 좋을 것 같아요!!

2024-04-25 05:19 UTC, devwqc requested changes
역시... 승구님 좋네요 좋아요❤️

2024-04-25 05:19 UTC, devwqc commented on package.json
> +    "lodash": "^4.17.21",
오호...! lodash로 디바운싱 적용하셨군요!👍

2024-04-25 05:19 UTC, devwqc commented on src/components/SideMenu/index.tsx
> +                  <Circle color={dashboard.color as string} small />
`Circle` 분리 너무 좋네요👍

2024-04-25 05:19 UTC, devwqc commented on src/pages/mydashboard/components/InvitedDashboard/InvitedDashboard.module.scss
> +.invitedBox > p {
`태그 선택자` 보다는 `클래스 선택자` 사용하면 더 좋을 거 같아요!

2024-04-25 05:19 UTC, devwqc commented on src/hooks/useInfiniteScroll.ts
> +) {
현재 무한 스크롤 훅을 사용하는 곳이 없는 거 같은데 맞을까요?

2024-04-25 05:19 UTC, devwqc commented on src/pages/mydashboard/components/InvitedDashboard/index.tsx
> +            {invitations.map((invitation) => (
invitations의 값이 `null`, `undefined`가 올 수 있어서 옵셔널 체이닝을 걸어주면 더 좋을 거 같아요👍
```suggestion
            {invitations?.map((invitation) => (
```

2024-04-25 05:19 UTC, devwqc commented on src/pages/mydashboard/components/SearchDashboard/index.tsx
> +  };
`onChange`의 핸들러로 `handleChange`가 더 적합해 보여요!
```suggestion
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    debouncing(e.target.value);
  };
```

2024-04-25 05:19 UTC, devwqc commented on src/pages/mydashboard/index.page.tsx
> +};
요거는 컴포넌트 함수 위쪽에 작성하는 게 더 가독성이 좋을 거 같아요 이 파일에 들어오자마자 SSR을 사용한다는 것을 알 수 있으니까

2024-04-25 05:29 UTC, devwqc commented on src/pages/mydashboard/components/InvitedDashboard/index.tsx
> +    const httpClient = new HttpClient(instance);
지금 사용처마다 HttpClient를 생성해서 인스턴스를 주입해주고 있는데 애초에 인스턴스를 주입해서 바로 사용할 수는 없을까요??

2024-04-25 05:31 UTC, q45402sk approved these changes

2024-04-25 06:10 UTC, milkboy2564 commented on src/pages/mydashboard/components/InvitedDashboard/index.tsx
> +    };
제네릭으로 Response Type을 넘겨주게 되면 타입 단언 쓰지 않더라도 response data의 타입 추론이 되지 않나요?!?

2024-04-25 06:10 UTC, milkboy2564 commented on src/pages/mydashboard/components/SearchDashboard/index.tsx
> +  invitee: { nickname: string; email: string; id: number };
중복되는 타입은 별도의 타입으로 분리해서 재사용해봅시다!

2024-04-25 06:10 UTC, milkboy2564 commented on src/pages/mydashboard/components/SearchDashboard/index.tsx
> +  };
핸들러 이름은 이벤트의 의도를 파악할 수 있게 지어주는게 좋습니다!
handeChange, handleClick, handleSubmit과 같은 범용적인 이름은 의미를 유추하는게 힘들어질  수 있어요!

2024-04-26 14:32 UTC, devwqc approved these changes

2024-04-27 10:30 UTC, closed without merging